version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shootout_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  mongo:
    image: mongo:4.4 # anything >5 fails immediately for me with CPU/AVX errors
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  postgres_data:
  mongo_data:

networks:
  db_net:
